
import { WarrantyClaim, SupportTicket, ClaimStatus, TicketStatus, TicketPriority } from './types';

export const BRANCHES = [
  'الرياض', 'جدة', 'الدمام', 'الخبر', 'الجبيل', 'مكة المكرمة', 'المدينة المنورة',
  'بريدة', 'عنيزة', 'حائل', 'تبوك', 'أبها', 'خميس مشيط', 'جازان', 'نجران', 'الطائف'
];

export const MOCK_CLAIMS: WarrantyClaim[] = [
  {
    id: 'WC001',
    vehicleVIN: 'SA123456789012345',
    branch: 'الرياض',
    issue: 'مشكلة في طلمبة الديزل',
    technicalReport: 'تم فحص السيارة وتبين وجود تسريب في طلمبة الديزل. القطعة تحتاج تغيير ضمن الضمان.',
    photos: [],
    videos: [],
    status: ClaimStatus.Pending,
    createdAt: new Date('2024-07-20T10:00:00Z'),
    updatedAt: new Date('2024-07-20T10:00:00Z'),
    comments: [],
  },
  {
    id: 'WC002',
    vehicleVIN: 'SA987654321098765',
    branch: 'جدة',
    issue: 'عطل في نظام التكييف',
    technicalReport: 'الكمبروسر لا يعمل. تم التحقق من الفيوزات والأسلاك وكلها سليمة.',
    photos: [],
    videos: [],
    status: ClaimStatus.Approved,
    createdAt: new Date('2024-07-19T14:30:00Z'),
    updatedAt: new Date('2024-07-20T09:00:00Z'),
    comments: [{ author: 'قسم الضمان', text: 'تمت الموافقة على تغيير الكمبروسر.', timestamp: new Date() }],
  },
  {
    id: 'WC003',
    vehicleVIN: 'SA123456789012345',
    branch: 'الرياض',
    issue: 'تآكل سريع في الإطارات الأمامية',
    technicalReport: 'يوجد تآكل غير طبيعي في الإطارات الأمامية من الداخل. قد يكون السبب مشكلة في زوايا العجلات.',
    photos: [],
    videos: [],
    status: ClaimStatus.RevisionNeeded,
    createdAt: new Date('2024-07-18T09:00:00Z'),
    updatedAt: new Date('2024-07-18T15:00:00Z'),
    comments: [{ author: 'قسم الضمان', text: 'يرجى إرفاق صور واضحة لتآكل الإطارات وتقرير فحص زوايا العجلات.', timestamp: new Date() }],
  },
  {
    id: 'WC004',
    vehicleVIN: 'SA555555555555555',
    branch: 'الدمام',
    issue: 'مشكلة في طلمبة الديزل',
    technicalReport: 'نفس مشكلة السيارة السابقة، تسريب واضح.',
    photos: [],
    videos: [],
    status: ClaimStatus.Rejected,
    createdAt: new Date('2024-07-17T11:00:00Z'),
    updatedAt: new Date('2024-07-17T18:00:00Z'),
    comments: [{ author: 'قسم الضمان', text: 'السيارة خارج فترة الضمان.', timestamp: new Date() }],
  },
  {
    id: 'WC005',
    vehicleVIN: 'SA777777777777777',
    branch: 'الجبيل',
    issue: 'صوت غريب من المحرك عند التشغيل',
    technicalReport: 'صوت طقطقة قادم من منطقة الصمامات.',
    photos: [],
    videos: [],
    status: ClaimStatus.Invoiced,
    createdAt: new Date('2024-07-15T08:00:00Z'),
    updatedAt: new Date('2024-07-16T12:00:00Z'),
    comments: [{ author: 'قسم الضمان', text: 'تمت الموافقة والإصلاح والفوترة.', timestamp: new Date() }],
  },
];

export const MOCK_TICKETS: SupportTicket[] = [
  {
    id: 'TS001',
    branch: 'الجبيل',
    issue: 'صعوبة في تشخيص عطل كهربائي',
    technicalReport: 'سيارة Hyundai Elantra 2023 لا تعمل. تم فحص البطارية والمولد وكل شيء سليم. نحتاج مساعدة في تتبع الدائرة الكهربائية.',
    photos: [],
    videos: [],
    priority: TicketPriority.Urgent,
    status: TicketStatus.Open,
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000), // 3 days ago
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    comments: [],
  },
  {
    id: 'TS002',
    branch: 'أبها',
    issue: 'استفسار عن أداة فحص خاصة',
    technicalReport: 'هل يتطلب فحص ناقل الحركة الجديد في طراز Palisade 2024 أداة خاصة؟ إذا كان الأمر كذلك، ما هو رقمها؟',
    photos: [],
    videos: [],
    priority: TicketPriority.Normal,
    status: TicketStatus.Solved,
    createdAt: new Date('2024-07-20T11:00:00Z'),
    updatedAt: new Date('2024-07-20T16:00:00Z'),
    comments: [{ author: 'الدعم الفني', text: 'نعم، تحتاج إلى أداة رقم 9988-ABC. تم إرسال نشرة فنية إلى بريدك.', timestamp: new Date() }],
  },
  {
    id: 'TS003',
    branch: 'الرياض',
    issue: 'مشكلة متكررة في حساس الأكسجين',
    technicalReport: 'تم تغيير حساس الأكسجين لسيارة Sonata 2022 ثلاث مرات خلال شهرين وما زال ضوء المحرك يضيء. ما هو الإجراء التالي؟',
    photos: [],
    videos: [],
    priority: TicketPriority.Urgent,
    status: TicketStatus.InProgress,
    createdAt: new Date('2024-07-21T09:30:00Z'),
    updatedAt: new Date('2024-07-21T14:00:00Z'),
    comments: [{ author: 'الدعم الفني', text: 'جاري مراجعة المخططات الكهربائية والبحث عن حالات مشابهة. قد تكون المشكلة من الظفيرة. سنعود إليك قريباً.', timestamp: new Date() }],
  },
];
